### ISSUE TITLE
Feature request: json output

### ISSUE THREAD

**Issue by 2rs2ts** [etopeter/kubectl-view-utilization#24]
Please allow for JSON output since it's easier for machines to parse.

Just an example, instead of:

```
cores    118 / 204   (58%)
memory   70G / 408G  (17%)
```

Maybe this (units in millicores and bytes, respectively):

```json
{
  "cores": {
    "requested": 118000,
    "allocatable": 204000
  },
  "memory": {
    "requested": 73400320,
    "allocatable": 427819008
  }
}
```

**Comment by etopeter** [comment]
Thank you for submitting this feature request. I added initial PR with proposed changes. 
Added -o --output json/text option.

Any feedback is welcome.
