### ISSUE TITLE
Utilization % doesn't change when nodes are drained

### ISSUE THREAD

**Issue by 2rs2ts** [etopeter/kubectl-view-utilization#34]
Steps to reproduce:

1. `watch kubectl-view-utilization`
2. `kubectl drain` some nodes
3. you will see that %s don't change, neither does schedulable

I think this might be a flaw in kubernetes itself but maybe there is a workaround?

**Comment by etopeter** [comment]
Thank you for reporting this issue. Seems like we could use better filtering when it comes to gathering information about available nodes with READY state. In your case you're draining nodes which also cordons them and make them unschedulable. I will add test cases for that and proper patch.

**Comment by etopeter** [comment]
Proposed fix for this issue:
https://github.com/etopeter/kubectl-view-utilization/pull/new/node-schedulable-only

**Comment by etopeter** [comment]
This is now in [Releasev0.2.2](https://github.com/etopeter/kubectl-view-utilization/releases/tag/v0.2.2). Closing issue.
