### ISSUE TITLE
Problems with memory output

### ISSUE THREAD

**Issue by 2rs2ts** [etopeter/kubectl-view-utilization#56]
**Describe the bug**

The columns for Schedulable and Free for memory seem to always be 0 for me, and also if I add a node label selector or if I  the percent calculations for memory also mess up.

```
kubectl view-utilization
Resource      Requests  %Requests        Limits  %Limits   Allocatable  Schedulable    Free
CPU             159606         55        153587       53        288288       128682  128682
Memory    248603738112        112  249245466624      112  220657360896            0       0
```

```
kubectl view-utilization -l role=kube-worker
Resource      Requests  %Requests        Limits  %Limits  Allocatable  Schedulable   Free
CPU             152232         84        144281       80       180180        27948  27948
Memory    244533166080        Err  245171748864      Err            0            0      0
```

I looked into the source and didn't find anything wrong with the way the selector flag is being used, so then I looked at my nodes with `kubectl describe node`. Here is the Capacity and Allocatable of one of the nodes with the `role=kube-worker` label:

```
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         16
  ephemeral-storage:           65989144Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      31842064Ki
  pods:                        110
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         12
  ephemeral-storage:           35239910145
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      26902655374
  pods:                        110
```

Meanwhile here is a node without that label: 

```
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         36
  ephemeral-storage:           16447336Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      71930968Ki
  pods:                        110
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         36
  ephemeral-storage:           15157864833
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      71828568Ki
  pods:                        110
```

As you can see the units for memory are consistent for the node without the label. For the node with the label they're not (kibibytes versus bytes.)

I think the problem, at least when I provide the selector, is that the units don't match for the first node. Though I am not sure why Schedulable and Free have the issue of being always 0.

Semi-related issue (my units are different but it seems that the root cause of the units being inconsistent is the same as this issue): https://github.com/kubernetes/kubernetes/issues/74986

**System details**
- Operating system that client is running: Debian Buster
- kubectl client and server version `kubectl version`: 1.17.8
- view-utilization plugin version `kubectl view-utilization -v`: v0.3.2

**Comment by etopeter** [comment]
Hi @2rs2ts thank you for submitting this issuse. I think you're right about the memory units. To really see what's going on I would really appreciate if you could run this command (this is same as here: https://github.com/etopeter/kubectl-view-utilization/blob/master/kubectl-view-utilization#L139)

```
kubectl get nodes --field-selector=spec.unschedulable=false -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.status.allocatable.cpu}{'\t'}{.status.allocatable.memory}{'\n'}{end}"
```

If its a cluster you can't share node names you can just remove {.metadata.name} from the template.

On a side note `-l` parameter that filters out nodes is more intended to be used with subcommand `nodes` because it filters only nodes and not pods.
When you run kubectl view-utilization the default view takes 2 data points (all pods on cluster and all nodes). If you add -l label it will filter nodes but keep pods. That will make percentages and general numbers show weirdly. 
So it really make only sense to filter node labels with `kubectl view-utilization nodes` command. That will show only nodes in question.

**Comment by 2rs2ts** [comment]
@etopeter happy to provide the output.

```
ip-10-45-17-163.eu-central-1.compute.internal   28      60768081688
ip-10-45-18-16.eu-central-1.compute.internal    28      60768081688
ip-10-45-18-56.eu-central-1.compute.internal    36      71828568Ki
ip-10-45-21-153.eu-central-1.compute.internal   28      60768081688
ip-10-45-22-223.eu-central-1.compute.internal   28      60768081688
ip-10-45-23-121.eu-central-1.compute.internal   36      71828568Ki
ip-10-45-24-151.eu-central-1.compute.internal   28      60768073701
ip-10-45-24-23.eu-central-1.compute.internal    36      71828568Ki
ip-10-45-24-8.eu-central-1.compute.internal     28      60768073701
```

If it helps provide context, the ones with the `Ki` allocatable memory are all masters, I don't really care about them and that's why I only want to see utilization for the nodes with the `role=kube-worker` label.

To address your comment about the subcommand: in my example, I'm just trying to get a glance of the overall usage of the cluster but only with respect to the nodes with this label and the pods that are scheduled to them. I'm not interested in a per-node breakdown. Is this not supported?

**Comment by etopeter** [comment]
Thank you for providing additional input. Indeed it's the units that are not showing on some nodes. 
You can ignore my comment about the subcommand. Its actually not true, I was wrong saying labels will work only for node subcommand. It used to work like that in early implementation but it was later fixed.

I created a fix for memory units and it should be merged shortly. If you can please test master branch if that resolves this issue.

**Comment by 2rs2ts** [comment]
@etopeter just pulled it down and checked it. Looks great! thanks for the fix.
